# -*- coding: utf-8 -*-
"""statistics presentation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11xOb6BBUWa-BOt1Fo06XJbwml1qCMLwj

one way ANOVA and Tukey
"""

import io
import pandas as pd
from google.colab import files
uploaded = files.upload()
a1=[]
a2=[]

df = pd.read_excel("ANOVA.xlsx",sheet_name="失業率")
for i in range(30):
    n1 = df["失業率"][i+30]
    n2 = df["失業率"][i+90]
    a1.append(n1)
    a2.append(n2)
df1 = pd.DataFrame(a1 , columns=['value'])
df2 = pd.DataFrame(a2 , columns=['value'])
#print(df1)
#print(df2)

import scipy.stats
print( '1:',scipy.stats.shapiro(df1['value']) )
print( '2:',scipy.stats.shapiro(df2['value']) )

import scipy.stats
f_value, p_value = scipy.stats.f_oneway(df1,df2)
print(f_value)
print(p_value)

df1['城鄉'] = '城'
df2['城鄉'] = '鄉'

all_data = pd.concat([df1,df2],ignore_index=True) # 把資料作垂直黏貼
#all_data

!pip install bioinfokit

from bioinfokit.analys import stat
res = stat()
res.anova_stat(df=all_data, res_var='value', anova_model='value ~ C(城鄉)')
res.anova_summary

import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm

model = ols('value ~ C(城鄉)', data=all_data).fit()
anova_table = anova_lm(model, typ=2)

all_data['SSE'] = model.resid**2

grouped_sse = all_data.groupby('城鄉')['SSE'].sum()
grouped_mean = all_data.groupby('城鄉')['value'].mean()

grouped_df = pd.DataFrame({"城鄉": ['城',"鄉"],"group mean": grouped_mean.values,"SSE": grouped_sse.values,"Mean Square": grouped_sse.values / (model.df_resid / len(grouped_sse))})
grouped_df["group mean"] = grouped_df["group mean"].apply(lambda x: round(x, 2))
display(grouped_df)

from statsmodels.stats.multicomp import pairwise_tukeyhsd
model = ols('value ~ C(城鄉)', data = all_data).fit()
anova_table = sm.stats.anova_lm(model, typ=2)
tukey_result = pairwise_tukeyhsd(all_data['value'], all_data['城鄉'])

#print(tukey_result)

import statsmodels.stats.multicomp as mc
# 將結果轉換為DataFrame
tukey_df = pd.DataFrame(data=tukey_result._results_table.data[1:], columns=tukey_result._results_table.data[0])

display(tukey_df)

"""two way ANOVA and regression"""

import io
import pandas as pd
from google.colab import files
#uploaded = files.upload() # 上傳csv檔案
#df = pd.read_excel(("ANOVA.xlsx"),sheet_name="失業率")

a1=[]
a2=[]
a3=[]
a4=[]
for i in range(30):
    n1 = df["失業率"][i]
    n2 = df["失業率"][i+30]
    n3 = df["失業率"][i+60]
    n4 = df["失業率"][i+90]
    a1.append(n1)
    a2.append(n2)
    a3.append(n3)
    a4.append(n4)
df1 = pd.DataFrame(a1 , columns=['value'])
df2 = pd.DataFrame(a2 , columns=['value'])
df3 = pd.DataFrame(a3 , columns=['value'])
df4 = pd.DataFrame(a4 , columns=['value'])
#df2 = df["城鄉"]
#df3 = df["有無"]

#print(df3)

df1['城鄉'] = '城'
df2['城鄉'] = '城'
df3['城鄉'] = '鄉'
df4['城鄉'] = '鄉'

df1['有無'] = '無'
df2['有無'] = '有'
df3['有無'] = '無'
df4['有無'] = '有'


all_data = pd.concat([df1,df2,df3,df4],ignore_index=True) # 把資料作垂直黏貼
#all_data

#!pip install bioinfokit

#from bioinfokit.analys import stat
res = stat()
res.anova_stat(df=all_data, res_var='value', anova_model='value ~ C(城鄉)+C(有無)')
display(res.anova_summary)

#import statsmodels.api as sm
model = sm.formula.ols('value ~ C(城鄉) + C(有無) + C(城鄉):C(有無)', data=all_data).fit()

print(model.summary())